window.CISSP_DOMAINS = [
  {
    id: 1,
    title: "Security and Risk Management",
    weight: 16,
    slug: "cissp-domain-1.html",
    accent: "#9b5cff",
    subdomains: [
      {
        code: "1.1",
        title: "Understand, adhere to, and promote professional ethics",
        topics: ["ISC2 Code of Professional Ethics", "Organizational code of ethics"],
      },
      {
        code: "1.2",
        title: "Understand and apply security concepts",
        topics: [
          "Confidentiality, integrity, availability, authenticity, and nonrepudiation",
          "Five pillars of information security",
        ],
      },
      {
        code: "1.3",
        title: "Evaluate and apply security governance principles",
        topics: [
          "Alignment of the security function to business strategy, goals, mission, and objectives",
          "Organizational processes such as acquisitions, divestitures, and governance committees",
          "Organizational roles and responsibilities",
          "Security control frameworks including ISO, NIST, COBIT, SABSA, PCI, and FedRAMP",
          "Due care and due diligence",
        ],
      },
      {
        code: "1.4",
        title: "Understand legal, regulatory, and compliance issues that pertain to information security in a holistic context",
        topics: [
          "Cybercrimes and data breaches",
          "Licensing and intellectual property requirements",
          "Import and export controls",
          "Transborder data flow",
          "Privacy requirements such as GDPR, CCPA, PIPL, and POPIA",
          "Contractual, legal, industry standards, and regulatory requirements",
        ],
      },
      {
        code: "1.5",
        title: "Understand requirements for investigation types (i.e., administrative, criminal, civil, regulatory, industry standards)",
        topics: ["Administrative, criminal, civil, regulatory, and industry standards investigations"],
      },
      {
        code: "1.6",
        title: "Develop, document, and implement security policy, standards, procedures, and guidelines",
        topics: [],
      },
      {
        code: "1.7",
        title: "Identify, analyze, assess, prioritize, and implement Business Continuity (BC) requirements",
        topics: ["Business impact analysis (BIA)", "External dependencies"],
      },
      {
        code: "1.8",
        title: "Contribute to and enforce personnel security policies and procedures",
        topics: [
          "Candidate screening and hiring",
          "Employment agreements and policy-driven requirements",
          "Onboarding, transfers, and termination processes",
          "Vendor, consultant, and contractor agreements and controls",
        ],
      },
      {
        code: "1.9",
        title: "Understand and apply risk management concepts",
        topics: [
          "Threat and vulnerability identification",
          "Risk analysis, assessment, and scope",
          "Risk response and treatment",
          "Preventive, detective, and corrective controls",
          "Security and privacy control assessments",
          "Continuous monitoring and measurement",
          "Internal and external reporting",
          "Continuous improvement and risk maturity modeling",
          "Risk frameworks including ISO, NIST, COBIT, SABSA, and PCI",
        ],
      },
      { code: "1.10", title: "Understand and apply threat modeling concepts and methodologies", topics: [] },
      {
        code: "1.11",
        title: "Apply Supply Chain Risk Management (SCRM) concepts",
        topics: [
          "Risks from suppliers and providers such as tampering, counterfeits, and implants",
          "Third-party assessment and monitoring",
          "Minimum security requirements and service-level requirements",
          "Silicon root of trust, physically unclonable functions, and software bill of materials",
        ],
      },
      {
        code: "1.12",
        title: "Establish and maintain a security awareness, education, and training program",
        topics: [
          "Methods to increase awareness and training such as social engineering, phishing, champions, and gamification",
          "Periodic content reviews for emerging technologies such as cryptocurrency, AI, and blockchain",
          "Program effectiveness evaluation",
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Asset Security",
    weight: 10,
    slug: "cissp-domain-2.html",
    accent: "#ff3cae",
    subdomains: [
      {
        code: "2.1",
        title: "Identify and classify information and assets",
        topics: ["Data classification", "Asset classification"],
      },
      { code: "2.2", title: "Establish information and asset handling requirements", topics: [] },
      {
        code: "2.3",
        title: "Provision information and assets securely",
        topics: ["Information and asset ownership", "Asset inventory", "Asset management"],
      },
      {
        code: "2.4",
        title: "Manage data lifecycle",
        topics: [
          "Data roles including owners, controllers, custodians, processors, users, and subjects",
          "Data collection",
          "Data location",
          "Data maintenance",
          "Data retention",
          "Data remanence",
          "Data destruction",
        ],
      },
      { code: "2.5", title: "Ensure appropriate asset retention (e.g., End of Life (EOL), End of Support)", topics: [] },
      {
        code: "2.6",
        title: "Determine data security controls and compliance requirements",
        topics: [
          "Data states such as in use, in transit, and at rest",
          "Scoping and tailoring",
          "Standards selection",
          "Data protection methods including DRM, DLP, and CASB",
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Security Architecture and Engineering",
    weight: 13,
    slug: "cissp-domain-3.html",
    accent: "#ff547e",
    subdomains: [
      {
        code: "3.1",
        title: "Research, implement and manage engineering processes using secure design principles",
        topics: [
          "Threat modeling",
          "Least privilege",
          "Defense in depth",
          "Secure defaults",
          "Fail securely",
          "Segregation of Duties",
          "Keep it simple and small",
          "Zero trust or trust but verify",
          "Privacy by design",
          "Shared responsibility",
          "Secure access service edge",
        ],
      },
      {
        code: "3.2",
        title: "Understand the fundamental concepts of security models (e.g., Biba, Star Model, Bell-LaPadula)",
        topics: ["Biba, Star Model, Bell-LaPadula, and related models"],
      },
      { code: "3.3", title: "Select controls based upon systems security requirements", topics: [] },
      {
        code: "3.4",
        title: "Understand security capabilities of Information Systems (IS) (e.g., memory protection, Trusted Platform Module (TPM), encryption/decryption)",
        topics: ["Memory protection", "Trusted Platform Module", "Encryption and decryption"],
      },
      {
        code: "3.5",
        title: "Assess and mitigate vulnerabilities of security architectures, designs, and solution elements",
        topics: [
          "Client-based systems",
          "Server-based systems",
          "Database systems",
          "Cryptographic systems",
          "Industrial Control Systems",
          "Cloud-based systems",
          "Distributed systems",
          "Internet of Things",
          "Microservices and APIs",
          "Containerization",
          "Serverless",
          "Embedded systems",
          "High-Performance Computing systems",
          "Edge computing systems",
          "Virtualized systems",
        ],
      },
      {
        code: "3.6",
        title: "Select and determine cryptographic solutions",
        topics: [
          "Cryptographic life cycle such as keys and algorithm selection",
          "Symmetric, asymmetric, elliptic curve, and quantum cryptographic methods",
          "Public key infrastructure and quantum key distribution",
        ],
      },
      {
        code: "3.7",
        title: "Understand methods of cryptanalytic attacks",
        topics: [
          "Brute force",
          "Ciphertext only",
          "Known plaintext",
          "Frequency analysis",
          "Chosen ciphertext",
          "Implementation attacks",
          "Side-channel",
          "Fault injection",
          "Timing",
          "Man-in-the-Middle",
          "Pass the hash",
          "Kerberos exploitation",
          "Ransomware",
        ],
      },
      { code: "3.8", title: "Apply security principles to site and facility design", topics: [] },
      {
        code: "3.9",
        title: "Design site and facility security controls",
        topics: [
          "Wiring closets and intermediate distribution facilities",
          "Server rooms and data centers",
          "Media storage facilities",
          "Evidence storage",
          "Restricted and work area security",
          "Utilities and HVAC",
          "Natural and man-made environmental issues",
          "Fire prevention, detection, and suppression",
          "Redundant and backup power",
        ],
      },
      {
        code: "3.10",
        title: "Manage the information system lifecycle",
        topics: [
          "Stakeholder needs and requirements",
          "Requirements analysis",
          "Architectural design",
          "Development and implementation",
          "Integration",
          "Verification and validation",
          "Transition and deployment",
          "Operations, maintenance, and sustainment",
          "Retirement and disposal",
        ],
      },
    ],
  },
  {
    id: 4,
    title: "Communication and Network Security",
    weight: 13,
    slug: "cissp-domain-4.html",
    accent: "#ff7c4f",
    subdomains: [
      {
        code: "4.1",
        title: "Apply secure design principles in network architectures",
        topics: [
          "OSI and TCP/IP models",
          "IPv4 and IPv6 addressing such as unicast, broadcast, multicast, and anycast",
          "Secure protocols including IPSec, SSH, SSL, and TLS",
          "Implications of multilayer protocols",
          "Converged protocols such as iSCSI, VoIP, InfiniBand over Ethernet, and Compute Express Link",
          "Transport architecture including topology and data, control, and management planes",
          "Performance metrics such as bandwidth, latency, jitter, throughput, and signal-to-noise ratio",
          "Traffic flows such as north-south and east-west",
          "Physical segmentation including in-band, out-of-band, and air-gapped designs",
          "Logical segmentation including VLANs, VPNs, virtual routing, and virtual domains",
          "Micro-segmentation, overlays, distributed firewalls, routers, IDS, IPS, and zero trust",
          "Edge networks such as ingress, egress, and peering",
          "Wireless networks including Bluetooth, Wi-Fi, Zigbee, and satellite",
          "Cellular and mobile networks such as 4G and 5G",
          "Content distribution networks",
          "Software-defined networks, APIs, SD-WAN, and network functions virtualization",
          "Virtual Private Cloud",
          "Network observability, traffic shaping, capacity management, fault detection, and handling",
        ],
      },
      {
        code: "4.2",
        title: "Secure network components",
        topics: [
          "Infrastructure operation such as redundant power, warranty, and support",
          "Transmission media security and signal propagation quality",
          "Network Access Control systems",
          "Endpoint security",
        ],
      },
      {
        code: "4.3",
        title: "Implement secure communication channels according to design",
        topics: [
          "Voice, video, and collaboration such as conferencing and Zoom rooms",
          "Remote access for network administrative functions",
          "Data communications such as backhaul networks and satellite",
          "Third-party connectivity such as telecom providers and hardware support",
        ],
      },
    ],
  },
  {
    id: 5,
    title: "Identity and Access Management (IAM)",
    weight: 13,
    slug: "cissp-domain-5.html",
    accent: "#ffad42",
    subdomains: [
      {
        code: "5.1",
        title: "Control physical and logical access to assets",
        topics: ["Information", "Systems", "Devices", "Facilities", "Applications", "Services"],
      },
      {
        code: "5.2",
        title: "Design identification and authentication strategy (e.g., people, devices, and services)",
        topics: [
          "People, devices, and services",
          "Groups and roles",
          "Authentication, Authorization and Accounting",
          "MFA and password-less authentication",
          "Session management",
          "Registration, proofing, and establishment of identity",
          "Federated Identity Management",
          "Credential management systems and password vaults",
          "Single sign-on",
          "Just-In-Time access",
        ],
      },
      {
        code: "5.3",
        title: "Federated identity with a third-party service",
        topics: ["On-premise", "Cloud", "Hybrid"],
      },
      {
        code: "5.4",
        title: "Implement and manage authorization mechanisms",
        topics: [
          "Role-based access control",
          "Rule-based access control",
          "Mandatory access control",
          "Discretionary access control",
          "Attribute-based access control",
          "Risk-based access control",
          "Access policy enforcement, policy decision points, and policy enforcement points",
        ],
      },
      {
        code: "5.5",
        title: "Manage the identity and access provisioning lifecycle",
        topics: [
          "Account access review for users, systems, and services",
          "Provisioning and deprovisioning",
          "Role definition and transition",
          "Privilege escalation and sudo auditing",
          "Service account management",
        ],
      },
      { code: "5.6", title: "Implement authentication systems", topics: [] },
    ],
  },
  {
    id: 6,
    title: "Security Assessment and Testing",
    weight: 12,
    slug: "cissp-domain-6.html",
    accent: "#ffe84d",
    subdomains: [
      {
        code: "6.1",
        title: "Design and validate assessment, test, and audit strategies",
        topics: [
          "Internal assessments within organizational control",
          "External assessments outside organizational control",
          "Third-party assessments outside enterprise control",
          "On-premises, cloud, and hybrid locations",
        ],
      },
      {
        code: "6.2",
        title: "Conduct security control testing",
        topics: [
          "Vulnerability assessment",
          "Penetration testing and red, blue, or purple team exercises",
          "Log reviews",
          "Synthetic transactions and benchmarks",
          "Code review and testing",
          "Misuse case testing",
          "Coverage analysis",
          "Interface testing such as UI, network, and API testing",
          "Breach attack simulations",
          "Compliance checks",
        ],
      },
      {
        code: "6.3",
        title: "Collect security process data (e.g., technical and administrative)",
        topics: [
          "Technical and administrative data",
          "Account management",
          "Management review and approval",
          "Key performance and risk indicators",
          "Backup verification data",
          "Training and awareness",
          "Disaster Recovery and Business Continuity",
        ],
      },
      {
        code: "6.4",
        title: "Analyze test output and generate report",
        topics: ["Remediation", "Exception handling", "Ethical disclosure"],
      },
      {
        code: "6.5",
        title: "Conduct or facilitate security audits",
        topics: [
          "Internal audits within organizational control",
          "External audits outside organizational control",
          "Third-party audits outside enterprise control",
          "On-premises, cloud, and hybrid locations",
        ],
      },
    ],
  },
  {
    id: 7,
    title: "Security Operations",
    weight: 13,
    slug: "cissp-domain-7.html",
    accent: "#24d6ce",
    subdomains: [
      {
        code: "7.1",
        title: "Understand and comply with investigations",
        topics: [
          "Evidence collection and handling",
          "Reporting and documentation",
          "Investigative techniques",
          "Digital forensics tools, tactics, and procedures",
          "Artifacts from computers, networks, mobile devices, and data sources",
        ],
      },
      {
        code: "7.2",
        title: "Conduct logging and monitoring activities",
        topics: [
          "Intrusion detection and prevention",
          "Security Information and Event Management",
          "Continuous monitoring and tuning",
          "Egress monitoring",
          "Log management",
          "Threat intelligence, threat feeds, and threat hunting",
          "User and Entity Behavior Analytics",
        ],
      },
      { code: "7.3", title: "Perform Configuration Management (CM) (e.g., provisioning, baselining, automation)", topics: ["Provisioning", "Baselining", "Automation"] },
      {
        code: "7.4",
        title: "Apply foundational security operations concepts",
        topics: [
          "Need-to-know and least privilege",
          "Separation of Duties and responsibilities",
          "Privileged account management",
          "Job rotation",
          "Service-level agreements",
        ],
      },
      {
        code: "7.5",
        title: "Apply resource protection",
        topics: ["Media management", "Media protection techniques", "Data at rest and data in transit"],
      },
      {
        code: "7.6",
        title: "Conduct incident management",
        topics: ["Detection", "Response", "Mitigation", "Reporting", "Recovery", "Remediation", "Lessons learned"],
      },
      {
        code: "7.7",
        title: "Operate and maintain detection and preventative measures",
        topics: [
          "Firewalls such as next generation, web application, and network firewalls",
          "IDS and IPS",
          "Whitelisting and blacklisting",
          "Third-party provided security services",
          "Sandboxing",
          "Honeypots and honeynets",
          "Anti-malware",
          "Machine learning and AI-based tools",
        ],
      },
      { code: "7.8", title: "Implement and support patch and vulnerability management", topics: [] },
      { code: "7.9", title: "Understand and participate in change management processes", topics: [] },
      {
        code: "7.10",
        title: "Implement recovery strategies",
        topics: [
          "Cloud, onsite, and offsite backup storage strategies",
          "Cold and hot recovery site strategies",
          "Resource capacity agreements",
          "Multiple processing sites",
          "System resilience, high availability, QoS, and fault tolerance",
        ],
      },
      {
        code: "7.11",
        title: "Implement Disaster Recovery processes",
        topics: ["Response", "Personnel", "Communications", "Assessment", "Restoration", "Training and awareness", "Lessons learned"],
      },
      {
        code: "7.12",
        title: "Test Disaster Recovery Plans",
        topics: ["Read-through and tabletop", "Walkthrough", "Simulation", "Parallel", "Full interruption", "Stakeholder, test status, and regulator communications"],
      },
      { code: "7.13", title: "Participate in Business Continuity planning and exercises", topics: [] },
      {
        code: "7.14",
        title: "Implement and manage physical security",
        topics: ["Perimeter security controls", "Internal security controls"],
      },
      {
        code: "7.15",
        title: "Address personnel safety and security concerns",
        topics: [
          "Travel",
          "Security training and awareness such as insider threat, social media impact, and 2FA fatigue",
          "Emergency management",
          "Duress",
        ],
      },
    ],
  },
  {
    id: 8,
    title: "Software Development Security",
    weight: 10,
    slug: "cissp-domain-8.html",
    accent: "#34a4ff",
    subdomains: [
      {
        code: "8.1",
        title: "Understand and integrate security in the Software Development Life Cycle",
        topics: [
          "Development methodologies such as Agile, Waterfall, DevOps, DevSecOps, and SAFe",
          "Maturity models such as CMM and SAMM",
          "Operation and maintenance",
          "Change management",
          "Integrated Product Team",
        ],
      },
      {
        code: "8.2",
        title: "Identify and apply security controls in software development ecosystems",
        topics: [
          "Programming languages",
          "Libraries",
          "Tool sets",
          "Integrated Development Environment",
          "Runtime",
          "CI/CD",
          "Software configuration management",
          "Code repositories",
          "Application security testing including SAST, DAST, SCA, and IAST",
        ],
      },
      {
        code: "8.3",
        title: "Assess the effectiveness of software security",
        topics: ["Auditing and logging of changes", "Risk analysis and mitigation"],
      },
      {
        code: "8.4",
        title: "Assess security impact of acquired software",
        topics: [
          "Commercial off-the-shelf software",
          "Open source",
          "Third-party software",
          "Managed services such as enterprise applications",
          "Cloud services such as SaaS, IaaS, and PaaS",
        ],
      },
      {
        code: "8.5",
        title: "Define and apply secure coding guidelines and standards",
        topics: [
          "Security weaknesses and vulnerabilities at the source-code level",
          "Security of APIs",
          "Secure coding practices",
          "Software-defined security",
        ],
      },
    ],
  },
];
